/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategorySearchToolbar: typeof import('./src/components/search/CategorySearchToolbar.vue')['default']
    KeywordSearchBar: typeof import('./src/components/search/KeywordSearchBar.vue')['default']
    MainMenu: typeof import('./src/components/menu/MainMenu.vue')['default']
    MenuToggleButton: typeof import('./src/components/common/MenuToggleButton.vue')['default']
    QuickActionFab: typeof import('./src/components/common/QuickActionFab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHeaderBar: typeof import('./src/components/search/SearchHeaderBar.vue')['default']
    SearchResultContainer: typeof import('./src/components/search/SearchResultContainer.vue')['default']
  }
}
