/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumChaptersTab: typeof import('./src/components/album/AlbumChaptersTab.vue')['default']
    AlbumCommentsTab: typeof import('./src/components/album/AlbumCommentsTab.vue')['default']
    AlbumHeader: typeof import('./src/components/album/AlbumHeader.vue')['default']
    AlbumInfoTab: typeof import('./src/components/album/AlbumInfoTab.vue')['default']
    AlbumPreviewTab: typeof import('./src/components/album/AlbumPreviewTab.vue')['default']
    CategorySearchToolbar: typeof import('./src/components/search/CategorySearchToolbar.vue')['default']
    DownloadTaskCard: typeof import('./src/components/download/DownloadTaskCard.vue')['default']
    FavoriteFolderContextMenu: typeof import('./src/components/favorite/FavoriteFolderContextMenu.vue')['default']
    FavoriteFolderPicker: typeof import('./src/components/favorite/FavoriteFolderPicker.vue')['default']
    FavoriteSearchBar: typeof import('./src/components/favorite/FavoriteSearchBar.vue')['default']
    FavoriteSideMenu: typeof import('./src/components/favorite/FavoriteSideMenu.vue')['default']
    HorizontalPageView: typeof import('./src/components/reader/HorizontalPageView.vue')['default']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    KeywordSearchBar: typeof import('./src/components/search/KeywordSearchBar.vue')['default']
    MainMenu: typeof import('./src/components/menu/MainMenu.vue')['default']
    MenuToggleButton: typeof import('./src/components/common/MenuToggleButton.vue')['default']
    PdfChapterSheet: typeof import('./src/components/download/PdfChapterSheet.vue')['default']
    PdfExportBottomSheet: typeof import('./src/components/download/PdfExportBottomSheet.vue')['default']
    QuickActionFab: typeof import('./src/components/common/QuickActionFab.vue')['default']
    ReaderBottomToolbar: typeof import('./src/components/reader/ReaderBottomToolbar.vue')['default']
    ReaderSettingsPanel: typeof import('./src/components/reader/ReaderSettingsPanel.vue')['default']
    ReaderTopToolbar: typeof import('./src/components/reader/ReaderTopToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHeaderBar: typeof import('./src/components/search/SearchHeaderBar.vue')['default']
    SearchHistoryDropdown: typeof import('./src/components/history/SearchHistoryDropdown.vue')['default']
    SearchResultContainer: typeof import('./src/components/search/SearchResultContainer.vue')['default']
    VerticalScrollView: typeof import('./src/components/reader/VerticalScrollView.vue')['default']
  }
}
