import type { JmcomicClient } from '@/services/jmcomic/JmcomicClient'

/**
 * Explicitly shared JSON command/query surface. Android-only permissions,
 * host controls, updater calls, raw file paths and addListener stay outside.
 */
export const COMMON_BACKEND_METHODS = [
  'search',
  'categories',
  'getAlbum',
  'getPhoto',
  'getComments',
  'getFavorites',
  'toggleAlbumLike',
  'toggleAlbumFavorite',
  'manageFavoriteFolder',
  'preloadImages',
  'retryImage',
  'setCacheCapacity',
  'getCacheCapacityInfo',
  'getImageCacheContents',
  'clearImageCache',
  'setDownloadConcurrency',
  'setPreloadConcurrency',
  'getAllSettings',
  'setReaderPreloadPages',
  'setReaderDisplayMode',
  'setReaderAutoShowToolbarAtEnd',
  'downloadChapter',
  'getDownloadTasks',
  'cancelDownload',
  'pauseDownload',
  'resumeDownload',
  'deleteDownloaded',
  'getDownloadedPhoto',
  'getDomainStates',
  'reprobeDomains',
  'measureLatency',
  'getInitStatus',
  'login',
  'logout',
  'checkLoginState',
  'autoLogin',
  'getUserProfile',
  'getBrowseHistory',
  'getBrowseHistoryOverview',
  'recordBrowse',
  'clearBrowseHistory',
  'deleteBrowseItem',
  'getParseHistory',
  'addParseHistory',
  'clearParseHistory',
  'deleteParseItem',
  'getOfflineFolders',
  'createOfflineFolder',
  'renameOfflineFolder',
  'deleteOfflineFolder',
  'addOfflineFavorite',
  'removeOfflineFavorite',
  'getOfflineFavorites',
  'getAllOfflineFavorites',
  'getOfflineFavoritesTotalCount',
  'getAllOfflineFavoritesMerged',
  'moveAllOfflineFavorites',
  'copyOfflineFolder',
  'addOfflineFavoritesBatch',
  'mergeOfflineAllToFolder',
  'saveOfflineBackup',
  'loadOfflineBackup',
  'deleteOfflineBackup',
  'listOfflineBackupKeys',
] as const satisfies readonly (keyof JmcomicClient)[]

export type CommonBackendMethod = (typeof COMMON_BACKEND_METHODS)[number]
export type BackendClient = Pick<JmcomicClient, CommonBackendMethod>
