import type { JmcomicClient } from '@/services/jmcomic/JmcomicClient'

/**
 * 显式共享的 JSON command/query 接口白名单。
 * 仅保留与平台无关的结构化业务方法；Android 专属权限、宿主控制、更新器、
 * 原始文件路径以及事件订阅（addListener）都留在本白名单之外，由各自端口承载。
 */
export const COMMON_BACKEND_METHODS = [
  'search',
  'categories',
  'getAlbum',
  'getPhoto',
  'getComments',
  'getFavorites',
  'toggleAlbumLike',
  'toggleAlbumFavorite',
  'manageFavoriteFolder',
  'preloadImages',
  'retryImage',
  'setCacheCapacity',
  'getCacheCapacityInfo',
  'getImageCacheContents',
  'clearImageCache',
  'setDownloadConcurrency',
  'setPreloadConcurrency',
  'getAllSettings',
  'setReaderPreloadPages',
  'setReaderDisplayMode',
  'setReaderAutoShowToolbarAtEnd',
  'downloadChapter',
  'getDownloadTasks',
  'cancelDownload',
  'pauseDownload',
  'resumeDownload',
  'deleteDownloaded',
  'getDownloadedPhoto',
  'getDomainStates',
  'reprobeDomains',
  'measureLatency',
  'getInitStatus',
  'login',
  'logout',
  'checkLoginState',
  'autoLogin',
  'getUserProfile',
  'getBrowseHistory',
  'getBrowseHistoryOverview',
  'recordBrowse',
  'clearBrowseHistory',
  'deleteBrowseItem',
  'getParseHistory',
  'addParseHistory',
  'clearParseHistory',
  'deleteParseItem',
  'getOfflineFolders',
  'createOfflineFolder',
  'renameOfflineFolder',
  'deleteOfflineFolder',
  'addOfflineFavorite',
  'removeOfflineFavorite',
  'getOfflineFavorites',
  'getAllOfflineFavorites',
  'getOfflineFavoritesTotalCount',
  'getAllOfflineFavoritesMerged',
  'moveAllOfflineFavorites',
  'copyOfflineFolder',
  'addOfflineFavoritesBatch',
  'mergeOfflineAllToFolder',
  'saveOfflineBackup',
  'loadOfflineBackup',
  'deleteOfflineBackup',
  'listOfflineBackupKeys',
] as const satisfies readonly (keyof JmcomicClient)[]

export type CommonBackendMethod = (typeof COMMON_BACKEND_METHODS)[number]
/** 平台无关的结构化后端方法集，页面通过它访问 JSON 业务接口，不感知底层 transport。 */
export type BackendClient = Pick<JmcomicClient, CommonBackendMethod>
