package io.github.jukomu.picacomic;

/** Wire-value-free catalog option generated by native code. */
public final class PicacomicCatalogOption {
    public final String id;
    public final String label;
    public final String description;

    public PicacomicCatalogOption(String id, String label, String description) {
        if (id == null || id.isEmpty() || label == null || label.isEmpty()) {
            throw new IllegalArgumentException("catalog option id and label are required");
        }
        this.id = id;
        this.label = label;
        this.description = description == null ? "" : description;
    }
}
