-- Schema from v1.4.6 PdfStore, database version 9.
CREATE TABLE pdf_files (id INTEGER PRIMARY KEY AUTOINCREMENT,file_path TEXT NOT NULL UNIQUE,file_name TEXT NOT NULL,source_type TEXT NOT NULL CHECK(source_type IN ('imported','exported')),ownership TEXT NOT NULL CHECK(ownership IN ('external_reference','app_created')),chapter_link_status TEXT NOT NULL CHECK(chapter_link_status IN ('resolved','unresolved','multi_chapter')),album_id TEXT NOT NULL,album_title TEXT NOT NULL DEFAULT '',cover_url TEXT NOT NULL DEFAULT '',authors TEXT NOT NULL DEFAULT '',chapter_id TEXT,chapter_title TEXT NOT NULL DEFAULT '',chapter_sort_order INTEGER NOT NULL DEFAULT 0,is_single_episode INTEGER NOT NULL DEFAULT -1 CHECK(is_single_episode IN (-1,0,1)),folder_id TEXT,file_size INTEGER NOT NULL DEFAULT 0,page_count INTEGER NOT NULL DEFAULT 0,availability TEXT NOT NULL DEFAULT 'unknown' CHECK(availability IN ('unknown','available','missing','inaccessible','invalid')),verification_status TEXT NOT NULL DEFAULT 'unverified' CHECK(verification_status IN ('unverified','valid','corrupt','page_mismatch')),verification_error TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,verified_at INTEGER);

CREATE TABLE pdf_export_tasks (export_id TEXT PRIMARY KEY,batch_id TEXT NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('chapter','merged')),album_id TEXT NOT NULL,album_title TEXT NOT NULL DEFAULT '',cover_url TEXT NOT NULL DEFAULT '',authors TEXT NOT NULL DEFAULT '',is_single_episode INTEGER NOT NULL DEFAULT -1 CHECK(is_single_episode IN (-1,0,1)),chapter_id TEXT,display_title TEXT NOT NULL,save_path TEXT NOT NULL,allow_overwrite INTEGER NOT NULL DEFAULT 0 CHECK(allow_overwrite IN (0,1)),use_original INTEGER NOT NULL CHECK(use_original IN (0,1)),compression_ratio REAL NOT NULL,split_pages INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL,phase TEXT NOT NULL,current_page INTEGER NOT NULL DEFAULT 0,total_pages INTEGER NOT NULL DEFAULT 0,current_volume INTEGER NOT NULL DEFAULT 0,total_volumes INTEGER NOT NULL DEFAULT 0,snapshot_revision INTEGER NOT NULL DEFAULT 0,cancel_requested INTEGER NOT NULL DEFAULT 0 CHECK(cancel_requested IN (0,1)),error_code TEXT,error_message TEXT,created_at INTEGER NOT NULL,started_at INTEGER,updated_at INTEGER NOT NULL,completed_at INTEGER);

CREATE TABLE pdf_export_chapters (export_id TEXT NOT NULL,sequence INTEGER NOT NULL,album_id TEXT NOT NULL,chapter_id TEXT NOT NULL,chapter_title TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,expected_page_count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(export_id, sequence),FOREIGN KEY(export_id) REFERENCES pdf_export_tasks(export_id) ON DELETE CASCADE);

CREATE TABLE pdf_export_volumes (export_id TEXT NOT NULL,volume_index INTEGER NOT NULL,start_page INTEGER NOT NULL,end_page INTEGER NOT NULL,expected_page_count INTEGER NOT NULL,actual_page_count INTEGER NOT NULL DEFAULT 0,final_path TEXT NOT NULL,temp_path TEXT NOT NULL,work_dir TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',file_size INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL,completed_at INTEGER,PRIMARY KEY(export_id, volume_index),FOREIGN KEY(export_id) REFERENCES pdf_export_tasks(export_id) ON DELETE CASCADE);

CREATE TABLE pdf_store_meta (id INTEGER PRIMARY KEY CHECK(id=1),reset_notice_pending INTEGER NOT NULL DEFAULT 0 CHECK(reset_notice_pending IN (0,1)),last_reset_at INTEGER,reset_from_version INTEGER,reset_reason TEXT,updated_at INTEGER NOT NULL);

CREATE INDEX idx_pdf_files_source_created ON pdf_files(source_type, created_at DESC, id DESC);

CREATE INDEX idx_pdf_files_availability_updated ON pdf_files(availability, updated_at DESC, id DESC);

CREATE INDEX idx_pdf_tasks_status_updated ON pdf_export_tasks(status, updated_at DESC, export_id);
